bid_project/bid_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

bid_project/blog/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

bid_project/blog/models.py
from django.db import models


# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=150)
    date_added = models.DateTimeField(auto_now_add=True)


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'

bid_project/blog/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

bid_project/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    return render(request, 'blog/index.html')


def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'blog/topics.html', context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'blog/topic.html', context)


def new_topic(request):
    if request.method != 'POST':
        form = TopicForm
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:topics'))

    context = {'form': form}
    return render(request, 'blog/new_topic.html', context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('blog:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'blog/new_entry.html', context)


def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'blog/edit_entry.html', context)

bid_project/blog/templates/blog/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Бид!</title>
{% bootstrap_css %}
{% bootstrap_javascript %}
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
        <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'blog:index' %}">Главная страница!</a>
                 </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'blog:topics' %}">Темы!</a></li>
                    </ul>
                </div>
        </div>
</nav>
</body>

{% block content %}{% endblock content %}

bid_project/blog/templates/blog/edit_entry.html
{% extends "blog/base.html" %}
{% block content %}
    <p><a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'blog:edit_entry' entry.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
    <button name="submit">Сохранить</button>
    </form>
{% endblock content %}

bid_project/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block header %}
<div class='jumbotron'>
<h1>Записи, ура!</h1>
</div>
{% endblock header %}

{% block content %}
<h2>Есть контент!</h2>
{% endblock content %}

bid_project/blog/templates/blog/new_entry.html
{% extends "blog/base.html" %}
{% block content %}
    <p><a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></p>
    <p>Добваить новый пост:</p>
    <form action="{% url 'blog:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Добавить пост</button>
    </form>
{% endblock content %}

bid_project/blog/templates/blog/new_topics.html
{% extends "Blog/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Добавить новую тему:</h2>
        {% endblock header %}
            {% block content %}
        <form action="{% url 'blog:new_topic' %}" method='post'
            class="form">
                {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                <button name="submit" class="btn btn-primary">Добавить тему</button>
            {% endbuttons %}
        </form>
{% endblock content %}

bid_project/blog/templates/blog/topic.html
{% extends 'blog/base.html' %}
{% block header %}
    <h2>{{ topic }}</h2>
    {% endblock header %}
    {% block content %}
        <p>
            <a href="{% url 'blog:new_entry' topic.id %}">Новый пост</a>
        </p>
    {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
            </h3>
        </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
    </div> <!-- panel -->
    {% empty %}
    Ещё нет постов.
{% endfor %}
{% endblock content %}

bid_project/blog/templates/blog/topics.html
{% extends "blog/base.html" %}
{% block header %}
<h1>Темы</h1>
    {% endblock header %}
        {% block content %}
    <ul>
            {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
        <li>Ещё нет тем.</li>
            {% endfor %}
    </ul>
<h3><a href="{% url 'blog:new_topic' %}">Добавить новую тему</h3>
<a href="{% url 'blog:edit_entry' entry.id %}">Отредактировать</a>
{% endblock content %}